#!/usr/bin/env tsx
/**
 * Setup script to generate required environment variable secrets
 *
 * Usage:
 *   pnpm tsx scripts/setup-env.ts
 *
 * This will generate:
 *   - BETTER_AUTH_SECRET (base64 encoded, 32 bytes)
 *   - INTEGRATION_ENCRYPTION_KEY (hex encoded, 32 bytes = 64 hex characters)
 */

import { execSync } from "child_process";
import { existsSync, writeFileSync } from "fs";
import { join } from "path";

function generateSecret(length: number, encoding: "base64" | "hex"): string {
  const bytes = length;
  if (encoding === "base64") {
    return execSync(`openssl rand -base64 ${bytes}`, {
      encoding: "utf-8",
    }).trim();
  }
  return execSync(`openssl rand -hex ${bytes}`, { encoding: "utf-8" }).trim();
}

function main() {
  console.log("🔐 Generating required secrets for environment variables...\n");

  const betterAuthSecret = generateSecret(32, "base64");
  const integrationEncryptionKey = generateSecret(32, "hex");

  console.log("Generated secrets:\n");
  console.log("BETTER_AUTH_SECRET:");
  console.log(betterAuthSecret);
  console.log("\nINTEGRATION_ENCRYPTION_KEY:");
  console.log(integrationEncryptionKey);
  console.log("\n");

  // Check if .env.local exists
  const envLocalPath = join(process.cwd(), ".env.local");
  const envExamplePath = join(process.cwd(), ".env.example");

  if (existsSync(envLocalPath)) {
    console.log("⚠️  .env.local already exists. Not overwriting.");
    console.log("Please manually add these values to your .env.local file:\n");
    console.log(`BETTER_AUTH_SECRET=${betterAuthSecret}`);
    console.log(`INTEGRATION_ENCRYPTION_KEY=${integrationEncryptionKey}`);
  } else {
    // Create .env.local with generated secrets
    const envContent = `# Generated by setup-env.ts
# Database
DATABASE_URL=postgresql://user:password@localhost:5432/workflow_builder

# Better Auth
BETTER_AUTH_SECRET=${betterAuthSecret}
BETTER_AUTH_URL=http://localhost:3000

# App URL
NEXT_PUBLIC_APP_URL=http://localhost:3000

# Credentials Encryption Key
INTEGRATION_ENCRYPTION_KEY=${integrationEncryptionKey}

# AI Gateway (for AI workflow generation)
# Get your API key from: https://platform.openai.com/api-keys
AI_GATEWAY_API_KEY=your-openai-api-key-here

# Optional: OAuth Providers
# GITHUB_CLIENT_ID=
# GITHUB_CLIENT_SECRET=
# NEXT_PUBLIC_GITHUB_CLIENT_ID=

# GOOGLE_CLIENT_ID=
# GOOGLE_CLIENT_SECRET=
# NEXT_PUBLIC_GOOGLE_CLIENT_ID=
`;

    writeFileSync(envLocalPath, envContent);
    console.log("✅ Created .env.local with generated secrets!");
    console.log("📝 Please update the following values:");
    console.log("   - DATABASE_URL (your PostgreSQL connection string)");
    console.log("   - AI_GATEWAY_API_KEY (your OpenAI API key)");
    console.log("   - Optional: OAuth provider credentials\n");
  }

  console.log("🚀 Next steps:");
  console.log("   1. Update DATABASE_URL in .env.local");
  console.log("   2. Add your AI_GATEWAY_API_KEY");
  console.log("   3. Run: pnpm db:push");
  console.log("   4. Run: pnpm dev");
}

main();
